#! /bin/sh
### BEGIN INIT INFO
# Provides:          echo-proxy
# Required-Start:    
# Required-Stop:
# Default-Start:
# Default-Stop:
# Short-Description: echo-proxy service.
### END INIT INFO

PATH=/sbin:/bin:/opt/echo/bin

. /lib/lsb/init-functions

NAME=echo-proxy
DAEMON=/opt/echo/bin/echo-proxy
DAEMON_OPTS="-c /etc/echo/conf/nginx/echo_nginx.conf"
PIDFILE=/var/run/echo/echo-proxy.pid

test -x $DAEMON || exit 5

do_start () {
  if [ -e $PIDFILE ]; then
    status_of_proc -p $PIDFILE $DAEMON "$NAME process" && status="0" || status="$?"
    if [ $status = "0" ]; then
      exit # Exit
    fi
  fi
  log_daemon_msg "Starting the process" "$NAME"
  if start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS ; then
    log_end_msg 0
  else
    log_end_msg 1
  fi
}

do_stop() {
  if [ -e $PIDFILE ]; then
    status_of_proc -p $PIDFILE $DAEMON "Stoppping the $NAME process" && status="0" || status="$?"
    if [ "$status" = 0 ]; then
      start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE /bin/rm -rf $PIDFILE
    fi
  else
    log_daemon_msg "$NAME process is not running"
    log_end_msg 0
  fi
}

do_status() {
  if [ -e $PIDFILE ]; then
    status_of_proc -p $PIDFILE $DAEMON "$NAME process" && exit 0 || exit $?
  else
    log_daemon_msg "$NAME Process is not running"
    log_end_msg 0
  fi
}

case "$1" in
  start)
    do_start
    ;;

  stop)
    do_stop
    ;;
  restart)
    $0 stop && sleep 2 && $0 start
    ;;
  status)
    do_status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|status}"
    exit 2
  ;;
esac

